const FIELDS_TO_SAVE = [
  'id',
  'node_id',
  'full_name',
  'html_url',
  'description',
  'created_at',
  'updated_at',
  'pushed_at',
  'git_url',
  'ssh_url',
  'homepage',
  'language',
  'license',
  'forks',
  'open_issues',
  'watchers',
  'default_branch',
  'owner.id',
  'owner.login',
  'owner.avatar_url',
  'owner.gravatar_id',
  'owner.html_url',
  'owner.type',
  'has_issues',
  'has_projects',
  'has_wiki',
  'has_pages',
  'archived',
  'disabled',
  'size',
];

module.exports = FIELDS_TO_SAVE;
